import { createSlice } from "@reduxjs/toolkit";

// Define the initial state of the todos
const initialState = {
  menuState: false,
};

// Create a slice using createSlice function
const SideMenuSlice = createSlice({
  name: "SideMenu", // Name of the slice
  initialState: initialState, // Initial state of the slice
  reducers: {
    // Reducer functions
    toggleMenu: (state, action) => {
      state.menuState = action.payload;
    },
  },
});

// Extract the action creators from the slice
export const { toggleMenu } = SideMenuSlice.actions;

// Export the reducer function generated by the slice
export default SideMenuSlice.reducer;
